In [7]:
import numpy as np
import pandas as pd
from numpy import *

### 可通过python内置list转换创建数组

In [34]:
a = [1,2,3,4,5]
b = array(a)
b

array([1, 2, 3, 4, 5])

### 多维数组

In [38]:
c = array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

### 包含多少个元素

In [40]:
c.size

6

### 数组有几行几列 (行，列)

In [41]:
c.shape

(2, 3)

### 包含多少维度
 - 维度：数组内包含几个分组(行)

In [42]:
c.ndim

2

### 数组类型
 - 默认整数数组为int64类型

In [46]:
c.dtype

dtype('int64')

### 每个元素占用字节数

In [51]:
c.itemsize

8

### 更改类型
 - 通过astype()更改

In [56]:
c.astype('int16')

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [57]:
c.itemsize

8

In [69]:
d = array([[1, 2, 3],[4, 5, 6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
d.astype('int16')

array([[1, 2, 3],
       [4, 5, 6]])

In [71]:
d.itemsize

8