In [19]:
import numpy as np
import pandas as pd
from numpy import *

### 可通过python内置list转换创建数组

In [40]:
a = [1,2,3,4,5]
b = array(a)
print(b)


[1 2 3 4 5]


### asarray: 引用多维数组
 - 当传入的数组为ndarray类型时，不会进行拷贝，直接进行引用

In [41]:
c = asarray(b)
b[:]=6
print(b)
print(c)

[6 6 6 6 6]
[6 6 6 6 6]


### 多维数组

In [21]:
c = array([[1,2,3],[4,5,6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

### 包含多少个元素

In [22]:
c.size

6

### 数组有几行几列 (行，列)

In [23]:
c.shape

(2, 3)

### 获取维度
 - 维度：数组内包含几个分组(行)

In [24]:
c.ndim

2

### 获取数组类型
 - 默认整数数组为int64类型

In [25]:
c.dtype

dtype('int32')

### 每个元素占用字节数

In [26]:
c.itemsize

4

### 更改类型
 - 通过astype()更改，并将新的ndarry返回

In [66]:
c1 = c.astype(np.float64)

array([6., 6., 6., 6., 6.])

In [67]:
c.itemsize

4

In [92]:
print(c1)
print(c1.itemsize)

[1 2 3 4]
1


In [29]:
d = array([[1, 2, 3],[4, 5, 6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
c1 = array([1,2,3,4],int8)
print('before')
print(c1.dtype)
print(c1.itemsize)
c2 = c1.astype(np.int64)
print('after')
print(c2.dtype)
print(c2.itemsize)

before
int8
1
after
int64
8


- 使用asarray更改类型

In [94]:
c3 = asarray(c2,np.int8)
print(c2.dtype)
print(c2.itemsize)

int64
8


### 使用arange创建

In [32]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
arange(3,5,0.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

### reshape将数组分割
  - reshape(列，行)

In [37]:
e = arange(15).reshape(3,5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

 - 使用reshape必须平均分组且刚好分割完整

In [39]:
f = arange(15).reshape(2，4）

SyntaxError: invalid character in identifier (<ipython-input-39-a8aee49002ec>, line 1)

### ones
 - 创建全是1的数组
 

In [43]:
g = ones(10)
g

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### ones_like
- 根据传如ndarray的shape和dtype创建一个值为1的ndarray

In [50]:
h = ones_like(d)
h

array([[1, 1, 1],
       [1, 1, 1]])

### zeros、zeros_like

In [68]:
zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [69]:
zeros_like(d)

array([[0, 0, 0],
       [0, 0, 0]])

### empty、empty_like 之创建新数组，不传入新的值(内存中的值有可能为之前回收的值)

In [59]:
empty_like(d)

array([[  817209584,       32760,           2],
       [          0, -1191182336,         451]])

In [57]:
i = empty(5)
i

array([0.00000000e+000, 6.95169859e-310, 9.88131292e-324,             nan,
       9.58553575e-312])

### eye、identity 创建N✖N的矩阵，对角线为1

In [62]:
eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [78]:
j = array([1,2,3,4],int16)
j.dtype

dtype('int16')

In [79]:
j.itemsize

2

In [ ]:
- 使用另一个ndarray的dtype更改类型

In [97]:
k = arange(10)
asarray(k,j.dtype)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

## 运算
- 数组之间可以进行运算

In [126]:
c

array([6, 6, 6, 6, 6])

In [100]:
b

array([6, 6, 6, 6, 6])

In [125]:
b*c

array([36, 36, 36, 36, 36])

In [124]:
b+1

array([7, 7, 7, 7, 7])

In [127]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


### 索引、切片
- 切片和赋值(=)过程不会进行copy，而是对原数组直接引用(节省内存)

In [130]:
pwd

'G:\\code\\jupyter\\numpy'

- 一维数组

In [131]:
from numpy import *

In [134]:
a = arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
a[1]

1

In [137]:
a[1:5]

array([1, 2, 3, 4])

In [138]:
a_slice = _

In [140]:
a_slice

array([1, 2, 3, 4])

- 数组切片的更改也会修改原数组的值

In [142]:
a_slice[:] =77
print(a_slice)
print(a)

[77 77 77 77]
[ 0 77 77 77 77  5  6  7  8  9]


- 使用copy()对数组切片进行拷贝

In [144]:
a_slice_1 = a[4:].copy()
a_slice_1

array([77,  5,  6,  7,  8,  9])

In [146]:
a_slice_1[:]=10
print(a)
print(a_slice_1)

[ 0 77 77 77 77  5  6  7  8  9]
[10 10 10 10 10 10]


- 多维数组

In [150]:
a_2d = array([[1,2,3],[4,5,6],[7,8,9]])
a_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [152]:
a_2d[1][1]

5

In [155]:
a_2d[1,1]

5

- 如果省略的后边的索引，则会返回一个低一维度的数组
例如一个 2✖2✖3 的数组就是一个一个数组内有2个数组，这2个数组数组分别包含3个元素

In [161]:
a_3d = array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])
a_3d

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [163]:
a_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
old_values = a_3d[0].copy()

In [167]:
old_values[0] = 100
old_values

array([[100, 100, 100],
       [  4,   5,   6]])

In [169]:
a_3d[0][1]

array([4, 5, 6])

In [170]:
a_3d[0][1][2]

6

In [171]:
a_3d[1,0,1]

2

- 索引切片
 - 用，区分维度，由左到右，数组唯独从外到内

In [194]:
a3 = a_3d[1,:,:2]
a3

array([[1, 2],
       [4, 5]])

- 对切片后的数据更改

In [196]:
a3.shape

(2, 2)

In [202]:
a3[:] = 100
a3

array([[100, 100],
       [100, 100]])

- 原数组的值也被更改

In [203]:
a_3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[100, 100,   3],
        [100, 100,   6]]])

- 布尔型索引

In [204]:
b = arange(100)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

取列表中大于50的偶数

In [205]:
b>50

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [209]:
b % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [211]:
(b>50)&(b%2==0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False])

In [212]:
c = b[(b>50)&(b%2==0)].copy()
c

array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

### 花式索引

- 一维数组花式索引

In [232]:
d = arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
d[[1,3,-4,2]]

array([1, 3, 6, 2])

- 多维数组花式索引

In [220]:
c = zeros((8,4))
c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [222]:
for i in range(8):
    c[i] = i
c

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [238]:
c[[1,5,2,3,-5]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

- 花式索引在[[]]内使用，**[1:3,1:]**表示得出之前的结果上再进行切片

In [255]:
c[[1,5,2,3,-5]][1:3,1:]

array([[5., 5., 5.],
       [2., 2., 2.]])

### 搜索结果再进行索引，是在之前的花式索引结果之上的**每个**元素再次进行花式索引

In [258]:
c[[1,5,2,3,-5],[3]]

array([1., 5., 2., 3., 3.])