In [2]:
import numpy as np

In [10]:
a = np.arange(0,5,0.2)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

- 四舍五入，返回一个新的列表 np.round(a) 
- np.rint(a)

In [41]:
b = np.round(a)
b

array([0., 0., 0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 4., 4., 4., 4., 4., 5., 5.])

In [40]:
x = np.rint(a)
x

array([0., 0., 0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3.,
       3., 4., 4., 4., 4., 4., 5., 5.])

- 向下取整 np.floor(数组)
- 向上取整 np.ceil(数组)

In [21]:
c = np.floor(a)
c

array([0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3.,
       3., 3., 3., 4., 4., 4., 4., 4.])

In [22]:
d = np.ceil(a)
d

array([0., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3., 4.,
       4., 4., 4., 4., 5., 5., 5., 5.])

- 取绝对值


In [26]:
e = np.arange(-10,10)
e

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [27]:
np.abs(e)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0,  1,  2,  3,  4,  5,  6,
        7,  8,  9])

- 开根号 sqrt

In [31]:
f = np.array([1,4,9,16,25,36])
f

array([ 1,  4,  9, 16, 25, 36])

In [32]:
np.sqrt(f)

array([1., 2., 3., 4., 5., 6.])

- 计算指数 np.exp

In [34]:
np.exp(f)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15])

- 自然数对数 np.log()

In [37]:
np.log(f)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894])

- 向零取整,正数和负数 获取更接近0的整数

In [43]:
g = np.arange(-10,10,0.3)
g

array([-10. ,  -9.7,  -9.4,  -9.1,  -8.8,  -8.5,  -8.2,  -7.9,  -7.6,
        -7.3,  -7. ,  -6.7,  -6.4,  -6.1,  -5.8,  -5.5,  -5.2,  -4.9,
        -4.6,  -4.3,  -4. ,  -3.7,  -3.4,  -3.1,  -2.8,  -2.5,  -2.2,
        -1.9,  -1.6,  -1.3,  -1. ,  -0.7,  -0.4,  -0.1,   0.2,   0.5,
         0.8,   1.1,   1.4,   1.7,   2. ,   2.3,   2.6,   2.9,   3.2,
         3.5,   3.8,   4.1,   4.4,   4.7,   5. ,   5.3,   5.6,   5.9,
         6.2,   6.5,   6.8,   7.1,   7.4,   7.7,   8. ,   8.3,   8.6,
         8.9,   9.2,   9.5,   9.8])

In [45]:
np.trunc(g)

array([-10.,  -9.,  -9.,  -9.,  -8.,  -8.,  -8.,  -7.,  -7.,  -7.,  -6.,
        -6.,  -6.,  -6.,  -5.,  -5.,  -5.,  -4.,  -4.,  -4.,  -3.,  -3.,
        -3.,  -3.,  -2.,  -2.,  -2.,  -1.,  -1.,  -1.,  -0.,  -0.,  -0.,
        -0.,   0.,   0.,   0.,   1.,   1.,   1.,   2.,   2.,   2.,   2.,
         3.,   3.,   3.,   4.,   4.,   4.,   5.,   5.,   5.,   5.,   6.,
         6.,   6.,   7.,   7.,   7.,   8.,   8.,   8.,   8.,   9.,   9.,
         9.])

- 分离整数与小数为两个数组并返回  np.modf(a)

In [46]:
np.modf(g)

(array([-0.00000000e+00, -7.00000000e-01, -4.00000000e-01, -1.00000000e-01,
        -8.00000000e-01, -5.00000000e-01, -2.00000000e-01, -9.00000000e-01,
        -6.00000000e-01, -3.00000000e-01, -1.00000000e+00, -7.00000000e-01,
        -4.00000000e-01, -1.00000000e-01, -8.00000000e-01, -5.00000000e-01,
        -2.00000000e-01, -9.00000000e-01, -6.00000000e-01, -3.00000000e-01,
        -1.00000000e+00, -7.00000000e-01, -4.00000000e-01, -1.00000000e-01,
        -8.00000000e-01, -5.00000000e-01, -2.00000000e-01, -9.00000000e-01,
        -6.00000000e-01, -3.00000000e-01, -1.00000000e+00, -7.00000000e-01,
        -4.00000000e-01, -1.00000000e-01,  2.00000000e-01,  5.00000000e-01,
         8.00000000e-01,  1.00000000e-01,  4.00000000e-01,  7.00000000e-01,
         2.84217094e-14,  3.00000000e-01,  6.00000000e-01,  9.00000000e-01,
         2.00000000e-01,  5.00000000e-01,  8.00000000e-01,  1.00000000e-01,
         4.00000000e-01,  7.00000000e-01,  3.55271368e-14,  3.00000000e-01,
         6.0

- 两个相同结构数组按对应位置取最大值 np.maximum(a,b)
- 两个相同结构数组按对应位置取最小值 np.maximum(a,b)

In [50]:
h = np.array([1,2,3,4,5])
i =  np.array([5,4,3,2,1])
np.maximum(h,i)

array([5, 4, 3, 4, 5])

np.minimum(h,i)

## 数学和统计方法
- sum   求数组和
- cumsum  求累计的和，并返回一个列表
- mean  平均值
- std  标准差
- var  方差
- min  最小值
- max  最大值
- argmin  最小值索引
- argmax  最大值索引

In [55]:
h.sum()

15

In [58]:
h.cumsum()

array([ 1,  3,  6, 10, 15], dtype=int32)

In [60]:
h.mean()

3.0

In [62]:
h.std()

1.4142135623730951

In [63]:
h.var()

2.0

In [66]:
h.min()

1

In [68]:
h.max()

5

In [69]:
h.argmin()

0

In [72]:
h.argmax()

4

## 随机数组生成
- rand  给定形状生成随机数（0-1）
- randint 
- choice
- shuffle
- uniform

获取10个0-1的1维随机数组

In [82]:
np.random.rand(10)

array([0.05973927, 0.00389759, 0.91032468, 0.60680197, 0.94969488,
       0.27103296, 0.41762982, 0.13352749, 0.93418182, 0.72692158])

获取一个2维0-1的随机数数组,需要传入shape

In [90]:
np.random.rand(2,3)

array([[0.29376816, 0.17803   , 0.06339257],
       [0.27824486, 0.08406721, 0.8142342 ]])

获取10个从2到10(不包括10)之间的一维数组

In [91]:
np.random.randint(2,10,10)

array([4, 5, 9, 4, 4, 6, 5, 3, 7, 2])

获取shape =（3,5)从2到10(不包括10)之间的二维数组

In [8]:
np.random.randint(2,10,(3,5))

array([[9, 8, 5, 7, 4],
       [9, 3, 2, 8, 5],
       [3, 7, 7, 3, 8]])

- 从一个均匀分布(low,high,size)中随机采集size个数字，并返回一个ndarray

In [7]:
np.random.uniform(0,10,10)

array([8.45772102, 6.95655939, 0.23208512, 1.91124508, 8.23952342,
       0.77934239, 9.07738989, 2.78079321, 9.8227453 , 8.35540221])

 - 将数组顺序随机改变 shuffle(i)

In [12]:
i = np.arange(10)
i

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.shuffle(i)
i

array([3, 5, 9, 1, 2, 7, 6, 0, 8, 4])